version: '3.7'

services:

  # elasticsearch node 1
  elasticsearch_node1:
    container_name: elasticsearch_node1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=elasticsearch_node1
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch_node2,elasticsearch_node3
      - cluster.initial_master_nodes=elasticsearch_node1,elasticsearch_node2,elasticsearch_node3
      - xpack.security.enabled=false
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-volume-node1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elacticsearch_cluster


  # elasticsearch node 2
  elasticsearch_node2:
    container_name: elasticsearch_node2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=elasticsearch_node2
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch_node1,elasticsearch_node3
      - cluster.initial_master_nodes=elasticsearch_node1,elasticsearch_node2,elasticsearch_node3
      - xpack.security.enabled=false
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-volume-node2:/usr/share/elasticsearch/data
    networks:
      - elacticsearch_cluster

    
  # elasticsearch node 3
  elasticsearch_node3:
    container_name: elasticsearch_node3
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=elasticsearch_node3
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch_node1,elasticsearch_node2
      - cluster.initial_master_nodes=elasticsearch_node1,elasticsearch_node2,elasticsearch_node3
      - xpack.security.enabled=false
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-volume-node3:/usr/share/elasticsearch/data
    networks:
      - elacticsearch_cluster


  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch_node1:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch_node1:9200","http://elasticsearch_node2:9200","http://elasticsearch_node3:9200"]'
    ports:
      - 5601:5601
    networks:
      - elacticsearch_cluster

volumes:

  elasticsearch-volume-node1:
    driver: local

  elasticsearch-volume-node2:
    driver: local

  elasticsearch-volume-node3:
    driver: local

networks:
  elacticsearch_cluster:
    driver: bridge